version: 2

# sphinx configuration file
sphinx:
  configuration: docs/source/conf.py

# build in additional formats such as PDF and ePub
formats: all

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

python:
  install:
    - method: pip
      path: .